title: Jhey Pi
tagline: CANTANTE & COMPOSITOR
email: jp10.manager@gmail.com
description: >-
    Hola saludos mi gente!!! Agradecido con el apoyo de todos ustedes a mi música, en especial al EP Viral. Ya sumamos más de 64K en el video del tema promocional del disco 'Internet' y seguimos creciendo. Espero me sigan apoyando dándole like al video y sobre todo compartiendolo con tus amigos. Recuerda que junto a tu apoyo nuestra música seguirá llegando más lejos. Cuento contigo!!! Seguimos dándole duro.
url: "https://jheypi.com" # the base hostname & protocol for your site, e.g. http://example.com
author: Jhey Pi
twitter:
    username: jpoficial_10
    card: summary
plugins:
    - jekyll-seo-tag
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-paginate-v2
# Build settings
markdown: kramdown
remote_theme: ItsPatrq/minimal-music-project
permalink: /:title.html
pagination:
    enabled: true
    per_page: 4
    limit: 0
    sort_field: "date"
    sort_reverse: true

    exclude:
        - CHANGELOG.md
        - CNAME
        - Gemfile
        - Gemfile.lock
        - LICENSE
        - README.md
        - screenshot.png
        - docs/
        - node_modules
